const MESSAGE_CHAR_LIMIT = 500;
const MESSAGE_MIN_CHAR_LIMIT = 50;
const NAME_CHAR_LIMIT = 30;
const EMAIL_CHAR_LIMIT = 254;

export {
  EMAIL_CHAR_LIMIT,
  MESSAGE_CHAR_LIMIT,
  MESSAGE_MIN_CHAR_LIMIT,
  NAME_CHAR_LIMIT,
};
